### ISSUE TITLE
FTB launcher "home" tab just says loading constantly

### ISSUE THREAD

**Issue by Joslie** [FTBTeam/FTB-Unstable-1.16#1]
Around an hour ago I got kicked out of my FTB academy server & since the launchers "Home" tab just shows loading constantly

**Comment by Sunekaer** [comment]
Please report at https://github.com/FTBTeam/FTB-App/issues

**Comment by Novocastrian** [comment]
I've reported it as https://github.com/FTBTeam/FTB-App/issues/300
