### ISSUE TITLE
ExtraStorage Crash

### ISSUE THREAD

**Issue by Gaz492** [FTBTeam/FTB-Unstable-1.16#4]
**Describe the bug**
Game Crashes when opening Diamond crafter

**To Reproduce**
1. Open diamond crafter
4. See crash-report

**Expected behavior**
Game not to crash

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser N/A
 - Version 2004 (OS Build 19041.572)

**Additional context**
None

**Link to Log or Crash File Paste**
https://paste.feed-the-beast.com/view/697d9e52

**Comment by DinnerBeef** [comment]
I have found I have this same issue.

**Comment by manmaed** [comment]
+1

**Comment by Rushmead** [comment]
I have also had this issue.

**Comment by Sunekaer** [comment]
logs?

**Comment by manmaed** [comment]
https://pastebin.com/K7smsm4W

**Comment by Rushmead** [comment]
https://paste.feed-the-beast.com/view/697d9e52

**Comment by Rushmead** [comment]
Sorry had the wrong link in my clipboard https://pste.ch/iruterofar.rb

**Comment by Sunekaer** [comment]
Fixed released
