### ISSUE TITLE
Biomes You Go biomes not spawning alongside Biomes O' Plenty biomes

### ISSUE THREAD

**Issue by kdsfa** [FTBTeam/FTB-Unstable-1.16#8]
**Describe the bug**
I've read multiple times that Biomes You Go and Biomes O' Plenty are compatible with each other. I thought that BYG biomes are supposed to be generated next to the BOP biomes. Can anyone confirm this? Every world I made only generates BOP biomes. 

**To Reproduce**
1. Go to 'Singleplayer'
2. Click on 'Create New World'
3. Click on 'More World Options...'
4. Select 'World Type: Biomes O' Plenty'
5. Click on 'Create New World'
6. World with BOP biomes only

**Expected behavior**
Biomes You Go biomes and Biomes O' Plenty biomes in the same world. 

**Additional context**
Minecraft version: 1.16.3
Forge version: 34.1.25
Biomes O' Plenty version: BiomesOPlenty-1.16.3-12.0.0.409-universal
Biomes You Go version: byg-1.1.0-ALPHA-v8

**Comment by Sunekaer** [comment]
This is not something we have tested and would be a question of the devs of the 2 mods
